# Generated by Django 5.1.6 on 2025-02-19 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('artikelnummer', models.IntegerField(max_length=50)),
                ('beschreibung', models.CharField(max_length=255)),
                ('lagerbestand', models.IntegerField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mitarbeiter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('gehalt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('schichtzeiten', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pferd',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('gewicht', models.FloatField()),
                ('herkunft', models.CharField(max_length=50)),
            ],
        ),
    ]
